# Generated by Django 4.1.7 on 2023-04-02 11:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import internationalflavor.vat_number.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=20)),
                ('apartment_number', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{3}$', message='Enter the zip code in the format xx-xxx.')])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('vat_id_number', internationalflavor.vat_number.models.VATNumberField(countries=['PL'], null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customers.postaladdress')),
            ],
        ),
    ]
